# ===============================
# SPRING BOOT APPLICATION CONFIGURATION
# ===============================

logging:
  level:
    ROOT: info    # Sets the default logging level to "info" (basic logs)
    org:
      springframework:
        security: TRACE   # Enables detailed security logs (useful for debugging authentication)
      hibernate:
        SQL: DEBUG    # Logs all executed SQL queries (useful for debugging database operations)
        type:
          descriptor:
            sql: TRACE    # Provides detailed SQL type descriptor logs
    gp.graduationproject.summer_internship_back: DEBUG    # Enables debug logs for the main application package

spring:
  liquibase:
    enabled: false    # Disables Liquibase (database migration tool)

  profiles:
    active: dev   # Sets the active profile to "dev" (development environment)

  application:
    name: summer-internship   # Defines the application name

  datasource:
    type: com.zaxxer.hikari.HikariDataSource    # Uses HikariCP as the connection pool
    url: jdbc:postgresql://34.134.188.233:5432/summer_internship_db   # Database connection URL (PostgreSQL)
    username: postgres    # Database username
    password: umut62    # Database password (IMPORTANT: Do not expose credentials in production!)
    driver-class-name: org.postgresql.Driver    # PostgreSQL JDBC driver
    hikari:
      poolName: Hikari    # Names the database connection pool
      auto-commit: false    # Disables auto-commit for transactions (improves consistency)

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred    # Loads JPA repositories lazily (improves startup performance)

  jpa:
    open-in-view: false   # Prevents session from staying open across multiple transactions (improves performance)
    hibernate:
      ddl-auto: update    # Automatically updates the database schema (use "none" in production)
    show-sql: true    # Enables SQL query logging
    properties:
      hibernate:
        default_schema: public    # Sets the default schema to "public"
        format_sql: true    # Formats SQL queries for better readability

  servlet:
    multipart:
      enabled: true   # Enables file upload support
      max-file-size: 100MB    # Maximum allowed file size
      max-request-size: 100MB   # Maximum request size (including all files)

  mail:
    host: smtp.gmail.com    # SMTP server for sending emails (Gmail)
    port: 587   # SMTP port for secure connection
    username: mertdamburaci1@gmail.com    # Email account for sending messages
    password: wexewroagdpagyoa    # Application-specific password (DO NOT expose in production)
    properties:
      mail:
        smtp:
          auth: true    # Enables SMTP authentication
          starttls:
            enable: true    # Enables STARTTLS (secure email communication)

server:
  port: 8080    # Defines the port the application will run on (default: 8080)

okta:
  oauth2:
    client:
      registration:
        auth0:
          issuer: https://dev-rswrfezhup08dw27.us.auth0.com/    # OAuth2 authorization server
          client-id: eXTU0IJkmyPzsfemoiACekMJkXIIdeZq   # OAuth2 client ID
          client-secret: LO9qrprGxMNLvwit9W23amOXeeBiJ3I2K2XQu-9QFDVDzaEjmXKw0W6cyIYPZsHz   # OAuth2 client secret (DO NOT expose in public repositories)
          scope: openid,profile,email   # Requested OAuth2 scopes (identity, profile, and email access)