logging:
  level:
    ROOT: info
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    gp.graduationproject.summer_internship_back: DEBUG

spring:
  liquibase:
    enabled: false
  profiles:
    active: dev
  application:
    name: summer-internship
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://34.134.188.233:5432/summer_internship_db
    username: postgres
    password: umut62
    driver-class-name: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mertdamburaci1@gmail.com
    password: wexewroagdpagyoa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

okta:
  oauth2:
    client:
      registration:
        auth0:
          issuer: https://dev-rswrfezhup08dw27.us.auth0.com/
          client-id: eXTU0IJkmyPzsfemoiACekMJkXIIdeZq
          client-secret: LO9qrprGxMNLvwit9W23amOXeeBiJ3I2K2XQu-9QFDVDzaEjmXKw0W6cyIYPZsHz
          scope: openid,profile,email